version: '3'

services:
  test_db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3309:3306"
    deploy:
      resources:
        limits:
          memory: 1g
